data = [
 {
  "disease": "Brown spot",
  "overview": "Brown spot of rice caused by Bipolaris oryzae(telemorph=Cochliobolus miyabeanus)  It especially occurs in environments where water supply is scarce and it is often combined with imbalances in plant mineral nutrition, especially the lack of nitrogen. These factors are commonly associated with resource-poor farmers’ fields. which at this beginning of the 21st century, are still tilled by the majority of the most resource-poor farmers in the world.",
  "preventive_measure": ": Drought has long been recognized as a key factor favouring BS epidemics. water shortage enhances BSTemperature and humidity:  temperature and humidity, in the form of leaf wetness, interact on infection efficiency. Decreasing minimum temperature more several epidemic.Plant nutrition :More the fertile land low chances of bs pathogens.so, fertility decides the growth of pathogens.One element, silicon, stands apart from the others. Si exerts beneficial effects on plant growth and production by alleviating both biological injuries and physiological stresses. Si-based amendments appear to address one of the main causes for susceptibility and could be one avenue for the management of BS in areas where soils are low.",
  "symptoms": "athogens affect cultures from seedling to milk stage. Symptoms appear as small specks on coleoptiles, leaf blades, leaf sheaths and glumes, and are most prominent on leaf blades and glumes. Typical leaf spots are brown with a gray or whitish center, sesame-like, cylindrical or oval, usually with a yellow halo, but young spots are small, circular, dark brown or purplish-brown. Several spots grow together and the leaves dry out. Affected nurseries are often recognizable from a distance due to their burnt appearance from seedling death. In susceptible varieties, the spots are much larger and can reach lengths of 1 cm or more. Leaf sheath and coleoptile symptoms are similar to leaf symptoms.Black or dark brown spots develop on the glumes, resulting in discolored and shriveled grains. Under favorable conditions, the spots develop dark brown conidiophores and conidia, giving them a velvety appearance. The fungus can invade the glume and leave dark spots on the endosperm. Dark lesions may also be seen on young roots. Nodes and internodes are rarely infected. The pathogen has also been reported to cause brown to dark brown lesions (5-15 x 1-2 mm) on the panicle stalk at the junction of flag leaf and stem. These lesions usually spread beneath the pods to severe moist rot, partially filled brittle dull grains, and occasional drooping panicles. You can see the growth of mycelium. Symptoms of dry rot are seen as the infection spreads upwards. The fungus may also produce brown or grey-brown spots in the throat area compared to the blackening of throat burns.",
  "solution": "Host plant resistance (HPR): Spraying of conidial suspension at booting stage during evening hours and use of susceptible spreader genotype along with test genotypes has been advocated by several researchers for better disease development and uniform results .Host specific toxin of H. oryzae has also been utilized for identification of resistant plants\/calluses against brown spot.  partial and complete resistance to the BS pathogen is expressed by several genotypes under field conditions (Shukla et al. 1995). It seems that the sources of resistance amongst Oryza sativa entries are few and recent research (e.g. Goel et al. 2006) has been exploring other pools, especially O. nivara. Biological control: Trichoderma spp., well-known mycoparasites, can colonize roots internally and help improving nutrient uptake and mobilization, enhance nitrogen use efficiency, promote root growth and plant biomass, and improve tolerance to various physiological stresses, including soil salinity and drought through the reduction of oxidative damage that stresses cause.Seed treatments with Trichoderma viride or T. harzianum have also been effective method.Direct foliar application of T. harzianum has also been reported to reduce the disease intensity and significantly improve grain yield, total grain carbohydrate and protein, in addition to a significant improvement in the total photosynthetic pigments in rice leaves."
 },
 {
  "disease": "Leaf blast",
  "overview": "Rice blast is caused by fungus Magnaporthe oryzae. The disease outbreak depends on the weather and climatic conditions of the various regions. The disease's occurrence and symptoms vary from country to country. Susceptible cultivars cause huge rice production loss in yield.During sexual hybridization, pathogenic changes may provide evidence of pathogenic variation found at the asexual stage of the fungus.",
  "preventive_measure": "Incorporate or roll the rice stubble soon after harvest to promote early decomposition. Plant the least-susceptible varieties and use a broad-spectrum seed treatment. Grow rice in open fields free of tree lines particularly on east and south sides Grow rice in fields where flood levels are easily maintained. Damage from blast can be reduced by keeping soil flooded 2 to 4 inches deep from the time rice plants are 6 to 8 inches tall until draining for harvest. Draining for straighthead is incompatible with the flooding required for blast control, so avoid fields with a history of straighthead andvarieties susceptible to straighthead, or plant blast-resistant varieties in these fields.Seed over a range of time to spread the heading dates. However, avoid planting late because blast will be more severe.Seed to a stand of 15 to 20 plants per square foot.Avoid excessive nitrogen application rates and apply no more than 30 pounds per acre of nitrogen per application at midseason. In fields with a history of blast, always split applications.",
  "symptoms": "Blast symptoms can occur on leaves, leaf collars, nodes and panicles.Blast symptoms appear on leaves as elliptical spots with light-colored centers and reddish edges.Both the shape and the color vary depending on the environment, age of the lesion and rice variety. Lesions on leaf sheaths, which rarely develop, resemble those on leaves. The most serious damage occurs when the fungus attacks nodes just below the head,often causing the stem to break thus,this stage is called “rotten neck”.Blast damage at the nodes disrupts the flow of water and nutrients to the kernels, halting their development.",
  "solution": "Chemical control: It has been demonstrated that chemical inhibitors like carborpropamid can stop appressoria from penetrating rice epidermal cells, protecting the grain. the essential oils of Rosmarinus officinalis and Origanum vulgare to be efficient in vitro and offers therapy criteria."
 },
 {
  "disease": "Hispa",
  "overview": "Hispa armigera[Dicladispa armigera} is the main cause for rice hispa.The eggs are placed individually inside the leaf and hatch after three to four days. The young larvae then feed inside the leaf, causing yellow, withered areas. After about a week, the pupa develops inside the leaf and lasts for three to four days. The adult then lives for fifteen to sixteen days and feeds on the epidermis of the leaves. Particularly vulnerable to assault are young plants with fragile leaves, therefore soft kinds are preferred.",
  "preventive_measure": "No effective resistance trait to this pest is available in rice.  Use narrower plant spacing with greater leaf densities. Grow crops early in the season to avoid peak populations. Cut the shoot tip to prevent egg-laying. Collect adult bugs with a sweeping net, preferably early in the morning when they are less mobile. Remove any kind of weed from the rice field during the crop-free season. Infested leaves and shoots should he clipped and burned, or buried deep in the mud. Avoid excessive nitrogen fertilization in infested fields. Apply a crop rotation to break the life cycle of the pest. ",
  "symptoms": "Adult beetles consume the upper epidermis through external feeding, leaving a distinctive pattern of parallel white streaks along the leaf's principal axis. Large, white blotches may occur in cases of severe infection, which can potentially impact the veins. On the broken leaves, adults are frequently visible, usually on the upper side. The larvae tunnel along the veins and produce white patches as they feed on the green tissue that lies between the two leaf epidermises. By holding the damaged leaf up to the light or running your fingertips along the tunnel, you can find them. Infested leaves become brittle and appear white in the field. Severely damaged crops appear burned from a distance.",
  "solution": "Biological control:  In certain regions, the larval parasiloid Eulophus femoralis may help to lessen the hispa issue. The conservation of indigenous natural enemies may also play an important role in the management of this pest. For example, there are small waspsthat attack the eggs and larvae and a reduviid bug that eats on the adults. There are also three fungal pathogens that attack the adults. Chemical Control: Always take into account an integrated strategy that combines biological treatments that are accessible with preventative measures. Several chemical formulations with the active components chlorpyriphos, malathion, cypermethrin, and fenthoate could be employed to control populations in cases of severe infestation."
 },
 {
  "disease": "Healthy",
  "overview": " ",
  "preventive_measure": " ",
  "symptoms": "",
  "solution": " "
 }
]
def soln(disease):
    for _ in range(len(data)):
        if (data[_]['disease']==disease):
            return data[_]